### ISSUE TITLE
ブクマ関連画面で`RecyclerView`の`ViewHolder`再アタッチ例外が発生する場合がある

### ISSUE THREAD

**Issue by suihan74** [suihan74/Satena#134]
```
Fatal Exception: java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7303)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6426)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6310)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6306)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:902)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by suihan74** [comment]
フッター用`ViewHolder`を使いまわしているために発生していることを確認
