### ISSUE TITLE
フォロー取得失敗時にクラッシュする場合がある

### ISSUE THREAD

**Issue by suihan74** [suihan74/Satena#275]
```
Fatal Exception: com.suihan74.utilities.exceptions.TaskFailureException
       at com.suihan74.satena.scenes.preferences.ignored.UserRelationRepository.getFollowings(UserRelationRepository.java:220)
       at com.suihan74.satena.scenes.preferences.ignored.UserRelationRepository$getFollowings$1.invokeSuspend(UserRelationRepository.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7899)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:960)
```

**Comment by suihan74** [comment]
再現性が不明
