### ISSUE TITLE
ブクマ画面の戻るボタン押下時にクラッシュする場合がある

### ISSUE THREAD

**Issue by suihan74** [suihan74/Satena#437]
```
Fatal Exception: java.lang.IllegalStateException: Fragment no longer exists for key f#0: unique id 0e4623e3-799c-4c6f-b78f-5e91002adb84
       at androidx.fragment.app.FragmentManager.getFragment(FragmentManager.java:960)
       at androidx.viewpager2.adapter.FragmentStateAdapter.restoreState(FragmentStateAdapter.java:549)
       at androidx.viewpager2.widget.ViewPager2.restorePendingState(ViewPager2.java:350)
       at androidx.viewpager2.widget.ViewPager2.dispatchRestoreInstanceState(ViewPager2.java:375)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
       at android.view.View.restoreHierarchyState(View.java:20996)
       at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:639)
       at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3010)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3001)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2180)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:781)
       at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:692)
       at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:664)
       at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:436)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:552)
       at com.suihan74.satena.scenes.bookmarks.BookmarksActivity.onBackPressed(BookmarksActivity.java:141)
       at android.app.Activity.onKeyUp(Activity.java:3836)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2878)
       at android.app.Activity.dispatchKeyEvent(Activity.java:4161)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6278)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6144)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5814)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5871)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5847)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6005)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by suihan74** [comment]
環境依存で再現性不明。  
一旦、クラッシュする代わりにエラーログを送信してActivityを終了するようにした。
