### ISSUE TITLE
`SatenaApplication.registerNetworkCallback()`で`SecurityException`発生する環境あり

### ISSUE THREAD

**Issue by suihan74** [suihan74/Satena#459]
```
Non-fatal Exception: java.lang.SecurityException: Package android does not belong to 10060
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:3609)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3690)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4084)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4054)
       at com.suihan74.satena.SatenaApplication.registerNetworkCallback(SatenaApplication.kt:245)
       at com.suihan74.satena.SatenaApplication.onCreate(SatenaApplication.kt:200)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7273)
       at android.app.ActivityThread.access$1700(ActivityThread.java:251)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2070)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:8240)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:979)
```

**Comment by suihan74** [comment]
Android12でfixedになっているっぽい
https://issuetracker.google.com/issues/175055271
